# Generated by Django 6.0.1 on 2026-02-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concept2code', '0002_alter_task_topic_alter_topic_level_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='hints_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='score',
            field=models.IntegerField(default=100),
        ),
    ]
