# Generated by Django 6.0.1 on 2026-03-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concept2code', '0005_conceptprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='score_multiplier',
            field=models.IntegerField(default=1),
        ),
    ]
