# Generated by Django 6.0.1 on 2026-03-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concept2code', '0007_learningactivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conceptprogress',
            name='unlocked_at',
        ),
        migrations.AddField(
            model_name='conceptprogress',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='conceptprogress',
            name='concept',
            field=models.CharField(max_length=50),
        ),
    ]
